### ISSUE TITLE
can you explain if this gem is used to keep the ember-cli app inside the Rails repo? If so, where?

### ISSUE THREAD

**Issue by jasonfb** [rwz/ember-cli-rails#138]
I have an existing Rails app I'd like to use as an API and I'd like to build a new Ember app that will communicate to this Rails app as an API. I have read about Ember-rails vs. Ember-cli-rails and I understand an important consideration is whether or not your Ember-CLI app (1) lives inside the same repository as your Rails app and (2) is deployed as its own app or is mounted onto your existing Rails app as a Rack extension (do I have that right?)

So I started following along the README and followed the instructions until I got to this sentence:

"For each of your EmberCLI applications install the addon with:"

My problem is, I don't have an existing Ember app. Where do I create it? I understand I can create a new ember-cli app using ```ember new my-new-app``` --- but where *exactly* should I create this app? Does it live as its own folder in my Rails repo? Inside of ```app/``` ? Inside of ```app/ember/``` ?

Or, should I make a new repo outside of my existing Rails repo. (Seems like the gem wants to *let* me create the Ember app inside my Rails app-- isn't that the point here-- but gives me no guidance or suggestions as to actually where to put it)

Please let me know if I've missed something.

Thanks,

**Comment by TeknoFiend** [comment]
You should create the app at the root of your Rails app to use this gem. Just like what you have but if you are already using source control (eg Git) for the Rails app you'll want to pass the `--skip-git` flag: `ember new frontend --skip-git`. So the root of your Rails app will have `app`, `bin`, `config`, `frontend` etc.

The initializer that gets placed in `config/initializers/ember.rb` will specify the name (and thus directory name) for your app:

```
EmberCLI.configure do |c|
  c.app :frontend
end
```

You can change `frontend` in each of these examples to whatever you want to call your app but "frontend" is a good choice if you are only going to have one Ember app.

**Comment by jasonfb** [comment]
Awesome that makes so much sense now. So basically in this set up I am using my Rails app to *serve* my Ember app, is that right?

If I had them separated (like, a separate repo and deployed to a separate Heroku environment), I would not only not be using this Gem, but my other Heroku environment would be a Node environment, is that right?

So essentially the choices here is "Serve Ember through Rails" or "Serve Ember on its own using Node" -- I just want to make sure I understand my choices.

This Gem lets me serve Ember through Rails, but has the advantage of being able to use the ember-cli command line tools while working on the app inside of my existing Rails repo. 

 is that a good summation?

**Comment by TeknoFiend** [comment]
Right, you can serve through rails with this GEM (or roll your own way of integrating) or you can serve your Ember app somewhere else. You don't really need Node for that. There are quite a few ways to do it but some people in the community are coming together around a solution (check out this video from Ember Conf for more info: https://www.youtube.com/watch?v=4EDetv_Rw5U&list=PLE7tQUdRKcyacwiUPs0CjPYt6tJub4xXU&index=5).

You can use the ember-cli command line tools regardless of where your ember app lives (as long as you use Ember CLI which is definitely the way to go.

I don't know what the setup will be for Heroku but I don't think you need 2 buildpacks. The result when using this gem should be something like a traditional Rails app w/ some Javascript except that the Javascript ends up being responsible for all of the page (or as much as you want) instead of little bits and pieces.

Definitely look around on Stack Overflow for "ember cli rails". The first thing that popped up for me was related to Heroku. Also, you'll probably want to ask the kinds of questions you have there instead of submitting issues. I'm happy to answer to you'll likely get more/better responses there.

**Comment by jasonfb** [comment]
Yes I understand. Greatly appreciated. I will close the issue now and leave it for the github archive. Thanks again!
