### ISSUE TITLE
Dont Compile Ember CLI Twice

### ISSUE THREAD

**Issue by nahtnam** [rwz/ember-cli-rails#184]
Hey!

I was chatting on the community slack and someone mentioned that ember-cli is being compiled and compressed twice. Once by npm or whatever (IDK), and then again by rails. This may be a reason why compiling/deploying the rails site take over 10 minutes for me (and other on the community slack).

Would it be possible to somehow skip the rails compilation of **only** ember-cli? I still want other js files compiled.

Thanks.

**Comment by mxaly** [comment]
:+1: with two small ember apps it is painful

**Comment by nahtnam** [comment]
How so?

**Comment by fullofcaffeine** [comment]
Are you guys still experiencing it? It looks like it's building twice for me, too:

<img width="336" alt="screenshot_2015-08-05_19_00_05" src="https://cloud.githubusercontent.com/assets/81248/9100783/53cde276-3ba4-11e5-9b68-118176096482.png">

Is that what you're going through, too? Did you manage to solve it?

**Comment by nahtnam** [comment]
Yep, and I believe that's what's taking 15 minute deploy times. I haven't
been able to find a solution yet.

On Wed, Aug 5, 2015, 5:01 PM Marcelo de Moraes Serpa <
notifications@github.com> wrote:

> Are you guys still experiencing it? It looks like it's building twice for
> me, too:
>
> [image: screenshot_2015-08-05_19_00_05]
> <https://cloud.githubusercontent.com/assets/81248/9100783/53cde276-3ba4-11e5-9b68-118176096482.png>
>
> Is that what you're going through, too? Did you manage to solve it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rwz/ember-cli-rails/issues/184#issuecomment-128188324>
> .
>
-- 
Thanks.

**Comment by fullofcaffeine** [comment]
Yeah. I guess I will just put `ember-cli-rails` aside and use ember-cli directly. The reason I wanted to use `ember-cli-rails` was to keep things simpler at this point, but since it's a greenfield app, I don't think it's worth the effort. 

The ember app can then be directly served by `nginx` and Rails would just provide the API endpoint. I'm not really seeing any real advantages of using `ember-cli-rails` as opposed to `ember-rails`, but since `ember-cli` is *the* way to go right now when it comes to EmberJS, then `ember-rails` isn't relevant anymore, I guess.

**Comment by nahtnam** [comment]
BTW your screenshot is not what I am referring to. Its just building once (in the screenshot). If you wait a few minutes, you will see rails compiling the ember-cli-rails file for you (second time its being compiled), and it gets stuck for a while there.

**Comment by jfcouture** [comment]
Not sure if it's the same issue, but our deploys were also taking over 10 minutes. Turns out it was uglifier running twice, once from ember-cli-uglify and then by rails pipeline. Seems uglifying an already uglified big vendor.js was really slow.

In our case, removing ember-cli-uglify fixed the issue.

**Comment by nahtnam** [comment]
@jfcouture Thanks! That is the correct solution and it has reduced my build times to about 5 minutes which is much more reasonable!
