### ISSUE TITLE
Best practices for passing data from Rails to Ember app?

### ISSUE THREAD

**Issue by courthead** [rwz/ember-cli-rails#19]
Not sure if this is the appropriate place to ask, but using ember-cli-rails, how might one pass data directly from a Rails controller into the Ember app? Previously, with the ember-rails gem, one could, for example, add a script tag to their layout that modified the globally-accessible `App` namespace:

    <script type="text/javascript">
      App.set('apiKey', '<%= @api_key %>');
    </script>

It was also possible to add a `.erb` extension to JS files and then directly add variables from Rails:

    # /app/assets/javascripts/my-app/models/task.js.erb
    ...
    App.Task.reopenClass({
      MAX_NAME_LENGTH: <%= Task::MAX_NAME_LENGTH %>,
      MAX_DETAILS_LENGTH: <%= Task::MAX_DETAILS_LENGTH %>
    });

I always thought that these types of "bridges" between your Rails and Ember apps made a compelling case for using ember-rails and serving an Ember app from a layout file as opposed to making the Ember app a separate collection of static files that you can just put on S3. Are there ways to accomplish something similar with ember-cli-rails given Ember CLI's use of modules?

**Comment by rwz** [comment]
Forgot to mention, couple last versions actually pass environment values over to the ember process. Including the stuff that was manually added by gems like dotenv. So, you can maintain a single dotenv file and make sure that stuff from there goes to your ember-cli app as well.

Closing this issue for now, since it turned into kind of discussion thread. Suggestions and comments are still welcome though.

**Comment by rondale-sc** [comment]
:+1: Neat
