### ISSUE TITLE
Forward the Content Security Policy

### ISSUE THREAD

**Issue by glennfu** [rwz/ember-cli-rails#97]
I'm using this plugin to make it so the browser doesn't freak out when I access an API on a different host:
https://github.com/rwjblue/ember-cli-content-security-policy

Is there a way ember-cli-rails could pick up the Content Security Policy from the current environment and apply it when using the ember layout?

I know the backup solution is to just re-implement the headers on the Rails side, but thought it might be nice if this plugin could handle it.

**Comment by rwz** [comment]
If you're using EmberCLI Rails, your pages are always served by Rails. Using this plugin doesn't make sense, since it requires you to run Express build server and this is not happening. So I don't really see why try emulate express server behavior when you should just include relevant headers into Rails action serving your Ember views.

Soo, I don't really see the way this could work.
